name: google_sign_in_macos
description: macOS implementation of the google_sign_in plugin.
repository: https://github.com/flutter/plugins/tree/main/packages/google_sign_in/google_sign_in_macos
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+google_sign_in%22
version: 0.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: google_sign_in
    platforms:
      macos:
        dartPluginClass: GoogleSignInMacOS
        pluginClass: FLTGoogleSignInPlugin

dependencies:
  flutter:
    sdk: flutter
  # google_sign_in_platform_interface:: ^2.10.0
  google_sign_in_platform_interface:
    git:
      url: https://github.com/miquido/plugins
      path: packages/google_sign_in/google_sign_in_platform_interface
      ref: google_sign_in_macos

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# The example deliberately includes limited-use secrets.
false_secrets:
  - /example/macos/Runner/GoogleService-Info.plist
  - /example/macos/RunnerTests/GoogleSignInTests.m
  - /example/lib/main.dart
